### PR TITLE
Fix order of cascading style inheritance

### PR DESCRIPTION
**Pull request by isilher**
gettingsomewhere

Style inheritance was added in #125, but the order of applying them is reversed from the expected cascading result:

``` js
<HTMLView
  value="<b>RED<u>GREEN<i>BLUE</i></u></b>"
  stylesheet={{
    b: { color: 'red' },
    u: { color: 'green' },
    i: { color: 'blue' },
  }}
/>
```

screen shot 2017-07-19 at 17 46 52

This fix will add the parent styles *before* the child styles, fixing cascading inheritance as expected:

screen shot 2017-07-19 at 17 46 24

### CODE REVIEW

**Comment by richchurcher** [comment]
@isilher Nice catch! Now, this might be a chance to fix something that's been bugging me... all the empty objects getting passed in to the style array. Even with your fix above, we still have three successive objects with the `color` prop which clutters things up a fair bit. What if instead we just did this:
```
  function inheritedStyle(parent) {
    if (!parent) return null;
    const style = StyleSheet.flatten(opts.styles[parent.name]) || {};
    const parentStyle = inheritedStyle(parent.parent) || {};
    return {...parentStyle, ...style};
  }
```
This way, every component will have just two objects passed to the style array: the default style and the custom. If there's a `color` prop on `style`, it'll overwrite `parentStyle`. It's only a shallow clone, but that shouldn't matter as we're not dealing with nested Sass or LESS.

If you like this, drop it in and update the snapshots (you'll need to import `StyleSheet` for the static `flatten`) and we'll be good to merge.

**Comment by isilher** [comment]
@richchurcher I implemented part of your suggestion: I could not find a difference with or without the `StyleSheet.flatten`. Combining the object already takes care of any duplication. Or perhaps I'm missing a use case?

**Comment by richchurcher** [comment]
@isilher Yeah, so the trick here is that if you can trust everyone to use plain objects as styles you'll be fine. However, the recommendation from React Native is that `StyleSheet`s are used (and it's all through the `react-native-htmlview` documentation).

Without `flatten`, these will fail since they need to be resolved (they only compile once, to an instance of `StyleSheet` which is basically properties associated with a reference number). If you try to use `Object.assign` or object spread with one you'll get an error about trying to assign with sources other than an object.

`flatten` works for both ordinary objects and `StyleSheets`, so it's best to use it here.

**Comment by isilher** [comment]
@richchurcher I understand now, and agree `StyleSheets` should be supported. Thanks for explaining!

**Pull request merged**
