### PR TITLE
0.12.1

### LINKED ISSUE #152: Replace View.propTypes with ViewPropTypes
Receiving this warning when using this module. 

```Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.```

Currently building with "react-native": "0.46.4"

### LINKED ISSUE #161: style: View.propTypes.style
Hello, even that on git is the version with style: ViewPropTypes.style, when I get the version over npm I receive the old one.

What I'm doing wrong? Version 0.12.0
P.S. I'm using React 16

### PR DESCRIPTION
**Pull request by richchurcher**
Hi! Just a quick patch release to overcome some frustrations users are having with more recent RN versions.

Fixes #152, closes #161.

### CODE REVIEW

**Comment by marcusmotill** [comment]
Ship it!

**Comment by jsdf** [comment]
Hey sorry for the delay, I'll try to take a look at this tonight

**Comment by PatrikTes** [comment]
Please ship it

**Comment by jsdf** [comment]
0.12.1 published to npm

**Comment by richchurcher** [comment]
Ty sir!

**Pull request merged**
