### PR TITLE
Fix line breaks for li

### PR DESCRIPTION
**Pull request by mdimovska**
Fix line breaks for `<li>` elements:
- add line break only if addLineBreaks is true 
- add line breaks only between `<li>` elements (do not set a line break for the last `<li>`, similar as it is done with paragraphs)

### CODE REVIEW

**Comment by mdimovska** [comment]
Hi @richchurcher, sorry for breaking the build. I fixed the linter errors. About the testing, there is already a test case, which I changed a little in order to correspond to the change I made in htmlToElement.js.
Please check the PR again. Thanks :)

**Comment by mdimovska** [comment]
I have questions related to line breaks in other elements (sorry, this is not very related to this PR). 

* Is there any specific reason why there are two \n for paragraph?
* Are these line breaks intended to behave similar as margins do (so that the separation between text looks nicer)? Or there is some other reason for this implementation?

Thanks :)

**Comment by richchurcher** [comment]
This is looking better. When I say add a test case, I mean one like this which specifically tests the `addLineBreaks` behaviour: https://github.com/jsdf/react-native-htmlview/blob/master/__tests__/HTMLView-test.js#L110-L126. So you want to make sure that it renders differently if that prop is false.

Regarding the breaks, I didn't write the original implementation but I can tell you that you can tweak margins fairly effectively if you turn 'em off: https://github.com/jsdf/react-native-htmlview/issues/142#issuecomment-331679944.

**Comment by chapeljuice** [comment]
Any idea when this is going to be released?!

**Pull request merged**
