### PR TITLE
Fix textAlign Center bug in stylesheets for values

### PR DESCRIPTION
**Pull request by RobPando**
Due to the nature of the implementation, `textAlign` does not work. Since the content of a tag is the one that is currently using the style passed in stylesheet so for example if I pass `p: { textAlign: 'center'}` in the stylesheet, the way the implementation works now is for each tag it creates a `<Text>` and places the content of that tag inside that text component but is also wrapped in another `<Text>` component so now if I pass a value of `<p>Hello World</p>` with the previously mentioned example stylesheet I would get 
```
<Text> # this is the 'p' tag
  <Text style={{ textAlign: 'center' }}>Hello World</Text>
</Text>
```

So its centering inside its own space, therefore the desire effect will never be seen. However, like in the web world you give the tag the class it should be:
```
<Text style={{ textAlign: 'center' }}> # this is the 'p' tag
  <Text>Hello World</Text>
</Text>
```

this would get the desired and expected behavior so it doesnt matter if you textAlign left a `h1` tag and textAlign center a `p` tag, the whole thing gets the desired behavior now. This PR does just that with a simple fix. I am open to any other cleaner approach, but the problem is that, the style is being placed in the wrong text component.

Ps: Sorry for the commit history, I first did a global fix, before finding the actual solution and changing it final.

### CODE REVIEW

**Comment by krzysztofciombor** [comment]
👍  It does seem to be working correctly.

**Comment by richchurcher** [comment]
@RobPando this seems promising! Can you sort out the conflict please?

**Comment by RobPando** [comment]
Of course, @richchurcher updated. Let me know of any changes please or suggestion to merge this in. Thank you!

**Comment by richchurcher** [comment]
@RobPando unfortunately I can't get this to work. It also seems to have the effect of removing other styles (try your branch with the following, for example):
```
import React from 'react';
import HTMLView from 'react-native-htmlview'
import { StyleSheet } from 'react-native';

export default class App extends React.Component {
  render() {
    const htmlContent = `
      
      <p>This is some <em>more</em> text to try to force a wrap. Wrapping is <strong>good</strong>.</p>
    `
    const sheet = StyleSheet.create({ p: { textAlign: 'center', backgroundColor: 'yellow' } })

    return (
      <HTMLView value={htmlContent} stylesheet={sheet} />
    )
  }
}
```
In 0.10 I get some formatting (it's a little flaky, but it works). With your changes, I get no formatting (and no textAlign). Maybe try it with a wide range of markup in the input, just to see the effect? I note also your branch is 0.9, so you might want to update and check against 0.10.

**Comment by RobPando** [comment]
@richchurcher updated! everything is working good now, I tried with a couple of complex scenarios and everything seems to be responding as expected. Please take a look at it again and let me know, thank you for pointing that out and hope this can be merged in. 🎊

**Comment by richchurcher** [comment]
Thanks for your patience and persistence!

**Pull request merged**
